# Required to run your project under the correct environment.
language: node_js

# Versions of nodejs you want your project run with.
node_js:
  - 0.11

# Commands to be run before your environment runs.
before_script:
  - npm install --global gulp

# Commands you want to run that will verify your build.
script: gulp qunit

# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: always

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-get update;
  - sudo apt-get install gcc-4.8 g++-4.8;
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20;
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
  - sudo g++ --version;
  - sudo apt-get update -qq;
after_success:
  - npm run-script coverage
cache:
  directories:
    - node_modules